name: Makefile CI

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master", "test" ]

jobs:
  build:
    name: Makefile CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        token: ${{ secrets.ORG_GH_TOKEN }}

    - name: Build project
      run: make
